name: Build OpenCV

on:
  workflow_dispatch:

jobs:
  build-opencv:
    runs-on: windows-latest

    steps:
      - name: Checkout OpenCV
        uses: actions/checkout@main
        with:
          repository: opencv/opencv
          ref: 5.0.0

      - name: Set up CMake build directory
        run: |
          mkdir build

      - name: Configure OpenCV with CMake
        working-directory: build
        shell: cmd
        run: |
          cmake .. -G "Visual Studio 18 2026" -A x64 ^
          -DCMAKE_CXX_STANDARD=23 ^
          -DCMAKE_ASM_COMPILER= ^
          -DCMAKE_INSTALL_PREFIX=install ^
          -DOPENCV_BIN_INSTALL_PATH=x64/bin ^
          -DOPENCV_LIB_INSTALL_PATH=x64/lib ^
          -DBUILD_SHARED_LIBS=ON ^
          -DBUILD_WITH_STATIC_CRT=ON ^
          -DBUILD_LIST=core,photo,imgproc ^
          -DBUILD_opencv_world=ON ^
          -DBUILD_EXAMPLES=OFF ^
          -DBUILD_TESTS=OFF ^
          -DBUILD_PERF_TESTS=OFF ^
          -DBUILD_DOCS=OFF ^
          -DWITH_IPP=OFF ^
          -DWITH_TBB=OFF ^
          -DWITH_OPENCL=OFF ^
          -DWITH_CUDA=OFF ^
          -DWITH_MSMF=OFF ^
          -DWITH_MFX=OFF

      - name: Build DLLs
        working-directory: build
        run: cmake --build . --config Release --target INSTALL

      - name: Upload DLLs and libs as artifact
        uses: actions/upload-artifact@main
        with:
          name: OpenCV for Windows (MSVC)
          path: |
            build/install/x64/bin/opencv_world*.dll
            build/install/x64/lib/opencv_world*.lib
            build/install/include
